# Generated by Django 5.2.8 on 2025-11-11 00:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComodoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Modelo de Cômodo')),
                ('icone', models.CharField(max_length=50, verbose_name='Nome do Arquivo do Ícone')),
            ],
        ),
        migrations.CreateModel(
            name='Comodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('icone', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comodos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField(default=0)),
                ('nivel', models.IntegerField(default=1)),
                ('streak_atual', models.IntegerField(default=0, verbose_name='Sequência Atual')),
                ('data_ultima_atividade', models.DateField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('intervalo_dias', models.IntegerField(default=1)),
                ('data_ultima_execucao', models.DateTimeField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('comodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='gestao.comodo')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conclusao', models.DateTimeField(default=django.utils.timezone.now)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='gestao.tarefa')),
            ],
        ),
        migrations.CreateModel(
            name='TarefaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Tarefa Modelo')),
                ('intervalo_dias_sugerido', models.IntegerField(default=1, verbose_name='Intervalo de Dias Sugerido')),
                ('comodo_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_template', to='gestao.comodotemplate')),
            ],
        ),
    ]
